import {chromium,firefox,webkit} from '../../tools/runtime-options/dirplayer-rs/node_modules/playwright/index.mjs';
import {mkdir,writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import path from 'node:path';

const engines={chromium,firefox,webkit};
const requested=process.argv.slice(2);
const out=path.resolve('artifacts/runtime-tests/browser-audio');
const base=process.env.FINDUS_TEST_URL || 'http://127.0.0.1:8766/';
await mkdir(out,{recursive:true});

// Insert analysers on the actual realtime output edges. This inspects audio
// generated by the game; it does not substitute audio files or script logic.
function instrumentAudio(){
  const Realtime=window.AudioContext || window.webkitAudioContext;
  const trace=window.__audioTrace={sources:[],outputs:[],samples:[],edges:[]};
  const ids=new WeakMap();let nextId=1;
  const id=node=>{if(!ids.has(node))ids.set(node,nextId++);return ids.get(node);};
  const connect=AudioNode.prototype.connect;
  AudioNode.prototype.connect=function(destination,...args){
    if(this.context instanceof Realtime && destination instanceof AudioDestinationNode){
      const analyser=this.context.createAnalyser();analyser.fftSize=2048;
      trace.outputs.push({node:this,analyser,sourceNode:id(this),destination:id(destination)});
      connect.call(this,analyser,...args);connect.call(analyser,destination);
      trace.edges.push([id(this),id(analyser),id(destination)]);
      return destination;
    }
    if(this.context instanceof Realtime && destination instanceof AudioNode)trace.edges.push([id(this),id(destination)]);
    return connect.call(this,destination,...args);
  };
  const prototype=window.BaseAudioContext?.prototype || Realtime.prototype;
  const create=prototype.createBufferSource;
  prototype.createBufferSource=function(...args){
    const source=create.apply(this,args);
    if(!(this instanceof Realtime))return source;
    const start=source.start,context=this;
    source.start=function(...args){
      const record={id:id(source),wallMs:performance.now(),contextTime:context.currentTime,
        duration:source.buffer?.duration,rate:source.buffer?.sampleRate,frames:source.buffer?.length,
        loop:source.loop,args,ended:null};
      trace.sources.push(record);
      source.addEventListener('ended',()=>{record.ended={wallMs:performance.now(),contextTime:context.currentTime};});
      return start.apply(source,args);
    };
    return source;
  };
  window.__audioSample=()=>{
    const outputs=trace.outputs.map(({node,analyser,sourceNode})=>{
      const data=new Float32Array(analyser.fftSize);analyser.getFloatTimeDomainData(data);
      let power=0,peak=0;for(const value of data){power+=value*value;peak=Math.max(peak,Math.abs(value));}
      return {sourceNode,rms:Math.sqrt(power/data.length),peak,gain:node.gain?.value};
    });
    let audioState=null;
    if(window.findus?.vm.get_audio_state){try{audioState=JSON.parse(window.findus.vm.get_audio_state());}catch{}}
    const sample={wallMs:performance.now(),contextTime:window.findus?.context.currentTime,
      contextState:window.findus?.context.state,frame:window.findus?.state.frame,
      loads:window.findus?.state.loads.length,outputs,audioState};
    trace.samples.push(sample);return sample;
  };
  setInterval(window.__audioSample,100);
}

const matrix=[];
for(const name of requested.length?requested:Object.keys(engines)){
  const browser=await engines[name].launch({headless:true});
  const report={engine:name,version:browser.version(),events:[],checks:{}};
  const digestPromises=[];
  const recordEngine=page=>page.on('response',response=>{
    if(response.url().endsWith('/vm_rust_bg.wasm'))digestPromises.push(response.body().then(body=>{
      const digest=createHash('sha256').update(body).digest('hex');
      if(report.wasmSha256&&report.wasmSha256!==digest)throw new Error('Runtime changed during audio/startup test');
      report.wasmSha256=digest;
    }));
  });
  try{
    const page=await browser.newPage({viewport:{width:1000,height:900}});
    recordEngine(page);
    page.setDefaultTimeout(45000);
    page.on('pageerror',e=>report.events.push({type:'pageerror',message:String(e)}));
    page.on('console',m=>{if(m.type()==='error')report.events.push({type:'console',message:m.text()});});
    await page.addInitScript(instrumentAudio);
    await page.goto(`${base}?movie=INTRO`);
    await page.locator('#start').click();
    await page.waitForFunction(()=>window.__audioTrace.sources.some(s=>s.duration>3&&!s.ended),null,{timeout:30000});
    await page.waitForTimeout(650);
    report.beforeMute=await page.evaluate(()=>window.__audioSample());
    await page.evaluate(()=>{
      if(!window.findus.vm.set_audio_muted)throw new Error('Rebuild required: set_audio_muted export missing');
      window.findus.vm.set_audio_muted(true);
    });
    await page.waitForTimeout(400);
    report.muted=await page.evaluate(()=>window.__audioSample());
    await page.evaluate(()=>window.findus.vm.set_audio_muted(false));
    await page.waitForTimeout(650);
    report.unmuted=await page.evaluate(()=>window.__audioSample());
    await page.waitForFunction(()=>window.__audioTrace.sources.some(s=>s.ended&&s.duration>3),null,{timeout:30000});
    await page.waitForTimeout(300);
    report.final=await page.evaluate(()=>({snapshot:window.findus.snapshot(),sources:window.__audioTrace.sources,edges:window.__audioTrace.edges,samples:window.__audioTrace.samples,loads:window.findus.state.loads}));
    report.checks.outputDetected=report.final.samples.some(s=>s.outputs.some(o=>o.rms>0.001));
    report.checks.muteSilent=report.muted.outputs.every(o=>o.rms<0.00001);
    report.checks.muteClockContinues=report.muted.contextState==='running' && report.muted.contextTime-report.beforeMute.contextTime>0.2;
    report.checks.finiteSourceEnds=report.final.sources.some(s=>s.ended&&s.duration>3&&!s.loop);
    report.checks.naturalEndTiming=report.final.sources.filter(s=>s.ended&&!s.loop).every(s=>Math.abs(s.ended.contextTime-s.contextTime-s.duration)<0.05);
    const channel2=report.final.samples.flatMap(s=>s.audioState?.channels.filter(c=>c.channel===2).map(c=>({busy:c.busy,samples:c.samples}))||[]);
    const busyIndex=channel2.findIndex(c=>c.busy&&c.samples===41984);
    report.checks.soundBusyReturnsFalse=busyIndex>=0&&channel2.slice(busyIndex+1).some(c=>!c.busy&&c.samples===41984);
    const current=report.beforeMute.audioState.channels.find(c=>c.busy);
    const mutedCurrent=report.muted.audioState.channels.find(c=>c.channel===current?.channel);
    report.checks.mutePreservesBusy=current?.busy&&mutedCurrent?.busy&&mutedCurrent.time_ms>current.time_ms;
    report.checks.mutePreservesAuthoredSettings=report.beforeMute.audioState.sound_level===report.muted.audioState.sound_level&&report.beforeMute.audioState.sound_enabled===report.muted.audioState.sound_enabled;
    report.checks.scriptErrors=report.final.snapshot.errors.length;
    await page.screenshot({path:path.join(out,`${name}-intro.png`)});
    await page.close();

    // Separate fresh context tests the complete launcher chain, not a direct
    // calendar entry with potentially missing globals.
    const startup=await browser.newPage({viewport:{width:1000,height:900}});
    recordEngine(startup);
    startup.setDefaultTimeout(60000);
    startup.on('pageerror',e=>report.events.push({type:'startup-pageerror',message:String(e)}));
    const calendarResponse=startup.waitForResponse(r=>/kalender\.(?:dxr|dcr)/i.test(r.url()),{timeout:60000});
    await startup.goto(base);
    await startup.locator('#start').click();
    await calendarResponse;
    await startup.waitForFunction(()=>window.findus?.state.loads.length>=4,null,{timeout:60000});
    await startup.waitForTimeout(2500);
    report.startup=await startup.evaluate(()=>({snapshot:window.findus.snapshot(),loads:window.findus.state.loads,contextState:window.findus.context.state}));
    await startup.screenshot({path:path.join(out,`${name}-calendar.png`)});
    report.checks.calendarLoaded=true;
    report.checks.calendarScriptErrors=report.startup.snapshot.errors.length;
    await startup.close();
    await Promise.all(digestPromises);
    report.verifiedAt=new Date().toISOString();
  }catch(error){report.error=String(error);}
  await writeFile(path.join(out,`${name}.json`),JSON.stringify(report,null,2));
  matrix.push(report);
  console.log(JSON.stringify({engine:name,version:report.version,checks:report.checks,error:report.error,events:report.events.slice(-5)}));
  await browser.close();
}
await writeFile(path.join(out,'matrix.json'),JSON.stringify(matrix.map(({final,...rest})=>rest),null,2));
